// Writes a NOTICE file for every workspace package with runtime dependencies.
// Reads pnpm-lock.yaml so every platform's binaries are listed and the output
// matches on any machine. --check exits 1 if a NOTICE is stale.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REGISTRY = 'https://registry.npmjs.org';
const FETCH_CONCURRENCY = 16;

const lock = parse(readFileSync(path.join(ROOT, 'pnpm-lock.yaml'), 'utf8'));
const importers = lock.importers ?? {};
const snapshots = lock.snapshots ?? {};

// Lockfile version -> snapshot key: "1.2.3(peer@1.0.0)" -> "name@1.2.3(peer@1.0.0)".
// An alias version such as "string-width@4.2.3" is already a key.
function snapshotKey(name, version) {
  const bare = version.replace(/\(.*$/, '');
  const at = bare.lastIndexOf('@');
  return at > 0 ? version : `${name}@${version}`;
}

function packageId(key) {
  const bare = key.replace(/\(.*$/, '');
  const at = bare.lastIndexOf('@');
  return { name: bare.slice(0, at), version: bare.slice(at + 1) };
}

function runtimeDeps(importerDir) {
  const entry = importers[importerDir] ?? {};
  return { ...entry.dependencies, ...entry.optionalDependencies };
}

// Third-party snapshot keys reachable from an importer, following workspace links.
function closure(importerDir) {
  const keys = new Set();
  const seenImporters = new Set();
  const stack = [];
  const visitImporter = (dir) => {
    if (seenImporters.has(dir)) return;
    seenImporters.add(dir);
    for (const [name, { version }] of Object.entries(runtimeDeps(dir))) {
      if (version.startsWith('link:')) {
        visitImporter(path.posix.normalize(path.posix.join(dir, version.slice(5))));
      } else {
        stack.push(snapshotKey(name, version));
      }
    }
  };
  visitImporter(importerDir);
  while (stack.length > 0) {
    const key = stack.pop();
    if (keys.has(key)) continue;
    keys.add(key);
    const snap = snapshots[key] ?? {};
    for (const [name, version] of Object.entries({ ...snap.dependencies, ...snap.optionalDependencies })) {
      stack.push(snapshotKey(name, version));
    }
  }
  return keys;
}

function licenseOf(meta) {
  if (typeof meta.license === 'string') return meta.license;
  if (meta.license?.type) return meta.license.type;
  if (Array.isArray(meta.licenses)) return meta.licenses.map((l) => l.type ?? l).join(' OR ');
  return 'UNKNOWN';
}

async function fetchLicenses(ids) {
  const out = new Map();
  const queue = [...ids];
  const worker = async () => {
    while (queue.length > 0) {
      const id = queue.pop();
      const { name, version } = packageId(id);
      const res = await fetch(`${REGISTRY}/${name.replace('/', '%2f')}/${version}`);
      if (!res.ok) throw new Error(`registry ${res.status} for ${name}@${version}`);
      out.set(id, licenseOf(await res.json()));
    }
  };
  await Promise.all(Array.from({ length: FETCH_CONCURRENCY }, worker));
  return out;
}

function render(pkgName, ids, licenses) {
  const lines = [
    pkgName,
    '',
    'This package includes the third-party software listed below, each under the',
    'license its package declares on npm. Generated by scripts/notice.mjs.',
    '',
  ];
  if (ids.length === 0) lines.push('No third-party runtime dependencies.');
  for (const id of ids) lines.push(`${id}  ${licenses.get(id)}`);
  return `${lines.join('\n')}\n`;
}

const targets = Object.keys(importers)
  .filter((dir) => dir !== '.')
  .filter((dir) => {
    const pkg = JSON.parse(readFileSync(path.join(ROOT, dir, 'package.json'), 'utf8'));
    return Object.keys(pkg.dependencies ?? {}).length > 0;
  })
  .sort();

const perTarget = targets.map((dir) => {
  const ids = [...new Set([...closure(dir)].map((key) => {
    const { name, version } = packageId(key);
    return `${name}@${version}`;
  }))].sort();
  return { dir, ids };
});
const licenses = await fetchLicenses(new Set(perTarget.flatMap((t) => t.ids)));

const check = process.argv.includes('--check');
const stale = [];
for (const { dir, ids } of perTarget) {
  const file = path.join(ROOT, dir, 'NOTICE');
  const pkgName = JSON.parse(readFileSync(path.join(ROOT, dir, 'package.json'), 'utf8')).name;
  const text = render(pkgName, ids, licenses);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (current === text) continue;
  if (check) stale.push(path.relative(ROOT, file));
  else writeFileSync(file, text);
}

if (check && stale.length > 0) {
  console.error(`Stale NOTICE files, run \`pnpm notice\`:\n${stale.map((f) => `  ${f}`).join('\n')}`);
  process.exit(1);
}
console.log(check ? 'NOTICE files are up to date.' : `Wrote NOTICE files for ${targets.length} packages.`);
